# Generated by Django 5.2 on 2025-04-03 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='incident',
            table='ai_safety_incidents',
        ),
    ]
